// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MNKR_AltMenuScreen3","status":true,"description":"レイアウトの異なるメニュー画面","parameters":{"displayWindow":"true","bgBitmapMenu":"","bgBitmapItem":"","bgBitmapSkill":"","bgBitmapEquip":"","bgBitmapStatus":"","bgBitmapOptions":"","bgBitmapFile":"","bgBitmapGameEnd":"","maxColsMenu":"4","commandRows":"2","isDisplayStatus":"true","display map name":"true","location string":"現在地:"}}
];
