// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MOG_BattleCursor","status":true,"description":"(v2.4.2 *) 対象選択にカーソルを追加します。","parameters":{"X-Axis":"0","Y-Axis":"0","Name Visible":"true","Name X-Axis":"0","Name Y-Axis":"0","Font Size":"18","Float Effect":"true","Sort X-Axis":"true","Window Visible":"false","Touch Selection":"true","Help All Allies":"全ての仲間","Help All Enemies":"全ての敵","Face Hud X-Axis":"0","Face Hud Y-Axis":"0"}}
];
