// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NRP_ShadowAndLevitate","status":true,"description":"v1.001 バトラーの影を設定＆浮遊効果の追加","parameters":{"<Enemy Shadow>":"","EnemyMakeShadow":"","EnemyShadowImage":"Shadow2","EnemyShadowScaleX":"a.width / shadow.width * 1.5","EnemyShadowScaleY":"a.width / shadow.width * 1.5","EnemyShadowX":"0","EnemyShadowY":"(a.height / 20) * -1","EnemyShadowZ":"2","EnemyShadowOpacity":"255","EnemyFloatHeight":"48","<Actor Shadow>":"","ActorShadowImage":"","ActorShadowScaleX":"","ActorShadowScaleY":"","ActorShadowX":"","ActorShadowY":"","ActorShadowZ":"","ActorShadowOpacity":"255","ActorFloatHeight":"24"}}
];
