// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GraphicalDesignMode","status":true,"description":"GUI画面デザインプラグイン\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"デザインモード":"false","自動保存":"false","モバイル版作成":"false","モバイル偽装":"false","ウィンドウ透過":"false","グリッドサイズ":"48","パディング":"0","フォントサイズ":"0","行の高さ":"0","背景透明度":"0","アイコンサイズ調整":"false","背景表示可否固定":"false","右クリックで消去":"false","メッセージウィンドウを無視":"false"}},
{"name":"TMRingCommand","status":true,"description":"マップシーンで使えるリングコマンドを追加します。","parameters":{"useEscape":"1","useCaption":"1","saveLastIndex":"0","openResetIndex":"0","openGoldWindow":"1","goldWindowX":"576","goldWindowY":"0","seOpenCommand":"{name: \"Cancel2\", volume: 90, pitch: 100, pan: 0}","seCloseCommand":"{name: \"Cancel2\", volume: 90, pitch: 100, pan: 0}","commandIconItem":"176","commandIconSkill":"76","commandIconEquip":"135","commandIconStatus":"84","commandIconFormation":"75","commandIconOptions":"83","commandIconSave":"225","commandIconGameEnd":"82","commandIconGoldLevelUp":"236","rotateDuration":"4","iconDistX":"16","iconDistY":"12","iconSelectScale":"1.5","captionWidth":"200","captionHeight":"48","captionShiftX":"0","captionShiftY":"-96"}},
{"name":"MNKR_TMRingCommandPatchFormation","status":true,"description":"TMRingCommand の並べ替え表示を簡易にします。","parameters":{}}
];
